package machine;

import java.util.Scanner;

public class CoffeeMachine {
    public static void main(String[] args) {
        CoffeeMachineManagement coffeeMachine= new CoffeeMachineManagement();

        try (Scanner scanner = new Scanner(System.in);
             Scanner scannerInt = new Scanner(System.in);
             Scanner scannerString = new Scanner(System.in);
        ) {
            while (true) {
                System.out.println("Write action (buy, fill, take, remaining, exit):");
                String action = scanner.nextLine();
                System.out.println();// For that new line space
                switch (action.toLowerCase()) {
                    case "buy":
                        System.out.println("What do you want to buy? 1 - espresso, 2 - latte, 3 - cappuccino, back - to main menu:");
                        String index = scannerString.nextLine().trim();
                        if ("1".equalsIgnoreCase(index)) {
                            boolean canAcceptPay = coffeeMachine.checkResources("espresso");
                            if (canAcceptPay) {
                                coffeeMachine.deductWater(250);
                                coffeeMachine.deductCoffeeBeans(16);
                                coffeeMachine.setMoney(4);
                                coffeeMachine.deductCups(1);
                            }
                        }
                        if ("2".equalsIgnoreCase(index)) {
                            boolean canAcceptPay = coffeeMachine.checkResources("latte");
                            if (canAcceptPay) {
                                coffeeMachine.deductWater(350);
                                coffeeMachine.deductMilk(75);
                                coffeeMachine.deductCoffeeBeans(20);
                                coffeeMachine.setMoney(7);
                                coffeeMachine.deductCups(1);
                            }
                        }
                        if ("3".equalsIgnoreCase(index)) {
                            boolean canAcceptPay = coffeeMachine.checkResources("cappuccino");
                            if (canAcceptPay) {
                                coffeeMachine.deductWater(200);
                                coffeeMachine.deductMilk(100);
                                coffeeMachine.deductCoffeeBeans(12);
                                coffeeMachine.setMoney(6);
                                coffeeMachine.deductCups(1);
                            }
                        }
                        if ("back".equalsIgnoreCase(index)) {
                            System.out.println(); // For that new line space
                            continue;
                        }
                        break;
                    case "fill":
                        System.out.println("Write how many ml of water you want to add:");
                        int water = scanner.nextInt();
                        coffeeMachine.setWater(water);

                        System.out.println("Write how many ml of milk you want to add");
                        int milk = scannerInt.nextInt();
                        coffeeMachine.setMilk(milk);

                        System.out.println("Write how many grams of coffee beans you want to add:");
                        int coffeeBeans = scannerInt.nextInt();
                        coffeeMachine.setCoffeeBeans(coffeeBeans);

                        System.out.println("Write how many disposable cups you want to add:");
                        int cups = scannerInt.nextInt();
                        coffeeMachine.setCups(cups);
                        scanner.nextLine(); // To consume the next line, generated by Enter.
                        System.out.println(); // To create a new line.
                        break;
                    case "take":
                        int amount = coffeeMachine.deductAllAmountMoney();
                        System.out.println("I gave you $%s".formatted(amount));
                        break;
                    case "remaining":
                        System.out.println(coffeeMachine.stateOfCoffeeMachine());
                        break;
                    case "exit":
                        System.exit(0);
                       break;
                }
            }
        }
    }
}
